---
name: Term-Menus-FromFile
version: 1.0.0
author:
  - 'Daniel T. Staal <DStaal@usa.net>'
abstract: Creates 'Term::Menus' menus from external files.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Term::Menus: 0
  perl: 5.6.0
build_requires:
  Test::Builder::Tester: 0
  Test::More: 0
provides:
  Term::Menus::FromFile:
    file: lib/Term/Menus/FromFile.pm
    version: 1.00.00
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
